### PR TITLE
Add and use outlined text in composite header

### LINKED ISSUE #3: Better color scheme
light blue and yellow are not mixing well - maybe black outline around colors, or different scale blue in heatmap

### PR DESCRIPTION
**Pull request by jaclyn-taroni**
Another option in response to #3

### CODE REVIEW

**Comment by kurtwheeler** [comment]
I guess we're leaving the old PNG around in case we want to go back to it? Approved

**Comment by jaclyn-taroni** [comment]
Yea maybe we want to change the heatmap color scheme instead @kurtwheeler

**Review by gwaybio — APPROVED** [review]
LGTM - will be good to generate a bunch of options i think.

since the file name changed, you may also want to update the raw link in the README

**Comment by jaclyn-taroni** [comment]
The header file name did not change (right?)

**Comment by gwaybio** [comment]
oh ya, good point

**Comment by dhimmel** [comment]
Seems like `cures_outlined_text.png` could also be saved as an SVG. When logos are involved, it's always good to retain vectors as long as possible.

**Pull request merged**
